apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mercadolibre
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: backend
    version: blue  # Will be switched during blue-green deployment
