apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mercadolibre

resources:
  - ../../base/common/namespace.yaml
  - ../../base/backend
  - ../../base/frontend
  - ingress.yaml
  - cert-manager/clusterissuer.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend
      namespace: mercadolibre
    spec:
      replicas: 3
      template:
        spec:
          containers:
          - name: backend
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
      namespace: mercadolibre
    spec:
      replicas: 3
      template:
        spec:
          containers:
          - name: frontend
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info

secretGenerator:
  - name: app-secrets
    literals:
      - DATABASE_URL=postgresql://user:password@db:5432/mercadolibre
    type: Opaque
