apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: mercadolibre
type: Opaque
stringData:
  # Backend secrets
  DATABASE_URL: "postgresql://user:password@db:5432/mercadolibre"
  JWT_SECRET: "your-jwt-secret-here"
  
  # Frontend secrets
  NEXT_PUBLIC_API_KEY: "your-api-key-here"
  
  # Docker registry credentials
  DOCKER_USERNAME: "your-dockerhub-username"
  DOCKER_PASSWORD: "your-dockerhub-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: mercadolibre
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "your-dockerhub-username",
          "password": "your-dockerhub-password",
          "email": "your-email@example.com",
          "auth": "base64-encoded-username:password"
        }
      }
    }
