apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - certificates.yaml
  - referencegrant.yaml
  - httproute-blue-green.yaml
  - virtual-services.yaml
  - destination-rules.yaml
  - rbac.yaml

namespace: mercadolibre