apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mercadolibre
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: frontend
    version: blue  # Will be switched during blue-green deployment
