version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=development
    volumes:
      - ../backend/data:/root/data
    networks:
      - app-network

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
