# docker/docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    container_name: mercadolibre-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATA_PATH=./data
      - ENV=production
    volumes:
      - ../backend/data:/root/data:ro
    networks:
      - mercadolibre-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    container_name: mercadolibre-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - mercadolibre-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mercadolibre-network:
    driver: bridge

    