name: CI - Backend

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yaml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yaml'

env:
  GO_VERSION: '1.22'
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: ldamasio/mercadolibre-backend

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
